language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
matrix:
  include:
    - python: "3.2"
      env: DJANGO_VERSION=1.6
    - python: "3.3"
      env: DJANGO_VERSION=1.6
install:
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - pip install -r requirements/base.txt --use-mirrors
script: python manage.py test
